#!/bin/bash
set -a

if [ "$#" -ne 1 ]; then
  echo "Usage: ./BuildMeOnPolaris <path to NEKRS_HOME>"
  echo -e "If okay with the default \$HOME/.local/nekrs, press ENTER to continue"
  echo "Or press Ctrl+C to quit"
  read -r -s KEY
  export NEKRS_HOME=$HOME/.local/nekrs
else
  export NEKRS_HOME=$1
fi

#... load the necessary modules here ...
module restore
module use /soft/modulefiles/
module load conda
conda activate
module load spack-pe-base cmake gcc-native/13
module list
#...

#... set the build and install directories
CWD=$PWD
echo -e "\033[35mInstalling nekRS at $NEKRS_HOME\033[m"
export INSTALL_DIR=$NEKRS_HOME
#...

#... set some environment variables
: ${ENABLE_SMARTREDIS:="OFF"}
export CC=cc
export CXX=CC
export FC=ftn
#...

#... build SmartRedis if enabled
if [ ${ENABLE_SMARTREDIS} == "ON" ]; then
  if [ -f "$NEKRS_HOME/SmartRedis/install/lib64/libsmartredis.so" ]; then
    echo -e "\033[35mFound SmartRedis at $NEKRS_HOME/SmartRedis/install/lib64/libsmartredis.so\033[m"
  else
    echo -e "\033[35mBuilding SmartRedis first ...\033[m"
    if [ ! -d "$NEKRS_HOME" ]; then
      mkdir -p $NEKRS_HOME
    fi
    cd $NEKRS_HOME
    git clone https://github.com/rickybalin/SmartRedis.git
    cd SmartRedis
    #pip install -e .
    make lib
    cd $CWD
    echo -e "\033[35mDone building SmartRedis\033[m"
    echo
  fi 
fi
#...

#... build nekRS
echo ""
if [ ${ENABLE_SMARTREDIS} == "ON" ]; then
  echo -e "\033[35mBuilding nekRS WITH SmartRedis ...\033[m"
  ./build.sh -DENABLE_SMARTREDIS=ON -DSMARTREDIS_INSTALL_DIR=$NEKRS_HOME/SmartRedis/install
else
  echo -e "\033[35mBuilding nekRS WITHOUT SmartRedis ...\033[m"
  ./build.sh
fi
#...

