#!/bin/bash
set -e -a

#... load the necessary modules here ...
module restore
module use /soft/modulefiles
module load PrgEnv-gnu
module load nvhpc-mixed/23.9
module load craype-accel-nvidia80
module load craype-x86-milan
module load spack-pe-base cmake

echo $(cc --version)
echo $(CC --version)
echo $(ftn --version)
echo $(gcc --version)
echo $(g++ --version)
echo $(gfortran --version)

#... set some environment variables
export NEKRS_HOME=$PWD/install_dir/nekrs
export PATH=$NEKRS_HOME/bin:$PATH 
