#!/bin/bash
set -a

if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
  echo "Usages:"
  echo "    $0 <system name> <path to NEKRS_HOME>"
  exit 1
fi

SYSTEM="${1,,}"
NEKRS_HOME=$2
PROJ_ID="datascience"
QUEUE="debug"

if [ ${SYSTEM} == "aurora" ]; then
  module load frameworks
elif [ ${SYSTEM} == "polaris" ]; then
  module use /soft/modulefiles/
  module load conda
  conda activate
  module load spack-pe-base cmake
elif [ ${SYSTEM} == "crux" ]; then
  module use /soft/modulefiles/
  module load PrgEnv-gnu/8.5.0
  module load gcc-native/12.3
  module load spack-pe-base/0.8.0
  module load cmake
  module load python/3.10.13
fi

echo "Setting up case:"
echo "    system: ${SYSTEM}"
echo "    NEKRS_HOME: ${NEKRS_HOME}"
echo

script_name=nrsrun_${SYSTEM}
NODES=`cat $PBS_NODEFILE | wc -l`

NEKRS_HOME=$NEKRS_HOME \
PROJ_ID=$PROJ_ID \
QUEUE=$QUEUE \
./${script_name} turbChannel $NODES 00:30

