#!/bin/bash
set -e

#--------------------------------------
: ${QUEUE:="debug-scaling"}
: ${NEKRS_GPU_MPI:=0}
: ${NEKRS_BACKEND:="dpcpp"}
: ${RANKS_PER_NODE:=12}
: ${NODES_PER_NEKRS:=1}
: ${CPU_BIND_LIST:="1:8:16:24:32:40:53:60:68:76:84:92"}
: ${CPU_BIND_LIST_EL:="1,8,16,24,32,40,53,60,68,76,84,92"}
: ${OCCA_DPCPP_COMPILER_FLAGS:="-O3 -fsycl -fsycl-targets=intel_gpu_pvc -ftarget-register-alloc-mode=pvc:auto -fma"}
: ${ONEAPI_SDK:=""}
: ${FRAMEWORKS_MODULE:="frameworks"}
: ${VENV_PATH:=""}
#--------------------------------------

source $NEKRS_HOME/bin/nrsqsub_utils
setup $# 1

#--------------------------------------
# Generate the run script
RFILE=run.sh
echo "#!/bin/bash -l" > $RFILE
echo "#PBS -S /bin/bash" >> $RFILE
echo "#PBS -N nekrs-ml" >> $RFILE
echo "#PBS -l select=${nodes}" >> $RFILE
echo "#PBS -l walltime=01:00:00" >> $RFILE
echo "#PBS -l filesystems=home:flare" >> $RFILE
echo "#PBS -A <project_name>" >> $RFILE
echo "#PBS -q ${QUEUE}" >> $RFILE
echo "#PBS -k doe" >> $RFILE
echo "#PBS -j oe" >> $RFILE
echo "cd \$PBS_O_WORKDIR" >> $RFILE

echo -e "\nexport TZ='/usr/share/zoneinfo/US/Central'" >> $RFILE

echo -e "\necho Jobid: \$PBS_JOBID" >>$RFILE
echo "echo Running on host \`hostname\`" >>$RFILE
echo "echo Running on nodes \`cat \$PBS_NODEFILE\`" >>$RFILE

echo "module restore" >> $RFILE
echo "module load ${FRAMEWORKS_MODULE}" >> $RFILE
echo "source ${VENV_PATH}" >> $RFILE
echo "module list" >> $RFILE

echo "export ZE_FLAT_DEVICE_HIERARCHY=FLAT" >> $RFILE
echo -e "\nexport NEKRS_HOME=$NEKRS_HOME" >>$RFILE
echo "export OCCA_DPCPP_COMPILER_FLAGS=\"$OCCA_DPCPP_COMPILER_FLAGS\"" >> $RFILE
echo "export FI_CXI_RX_MATCH_MODE=hybrid" >> $RFILE # required by parRSB

# Temporary workaround while waiting on bugfix in runtime
echo "export UR_L0_USE_COPY_ENGINE=0" >> $RFILE

# Calculate the number of nodes and ranks for the nekRS simulation
echo -e "\n# Calculate the number of nodes and ranks for the nekRS simulation" >>$RFILE
echo "RANKS_PER_NODE=${RANKS_PER_NODE}" >> $RFILE
echo "NODES_PER_NEKRS=${NODES_PER_NEKRS}" >> $RFILE
echo "NEKRS_RANKS=\$(( RANKS_PER_NODE * NODES_PER_NEKRS ))" >> $RFILE
echo "TOTAL_NODES=${nodes}" >> $RFILE
echo "TOTAL_RANKS=\$(( TOTAL_NODES * RANKS_PER_NODE ))" >> $RFILE

echo -e "\n# Build nekRS cache" >>$RFILE
echo "mpiexec -n \${RANKS_PER_NODE} -ppn \${RANKS_PER_NODE} --cpu-bind=list:${CPU_BIND_LIST} -- $NEKRS_HOME/bin/nekrs --setup ${case} --backend ${NEKRS_BACKEND} --build-only \${RANKS_PER_NODE}" >> $RFILE

echo -e "\n# Run initial nekRS simulation to generate high and low p order checkpoint files" >>$RFILE
echo "mpiexec -n \${NEKRS_RANKS} -ppn \${RANKS_PER_NODE} --cpu-bind=list:${CPU_BIND_LIST} -- $NEKRS_HOME/bin/nekrs --setup ${case} --backend ${NEKRS_BACKEND} 2>&1 | tee nekrs.log" >> $RFILE

echo -e "\n# Run ensemble of nekRS simulations starting from each high- and low-p checkpoint .f file" >>$RFILE
echo "python gen_ensemble_inputs.py ${case} \\" >> $RFILE
echo "    --p-orders 1,7 \\" >> $RFILE
echo "    --num-steps 200 \\" >> $RFILE
echo "    --nodes-per-member \${NODES_PER_NEKRS} \\" >> $RFILE
echo "    --ppn \${RANKS_PER_NODE} \\" >> $RFILE
echo "    --cpu-bind \"${CPU_BIND_LIST_EL}\" \\" >> $RFILE
echo "    --backend ${NEKRS_BACKEND} \\" >> $RFILE
echo "    --system aurora" >> $RFILE
echo "el start ./run_dir/config.json \\" >> $RFILE
echo "    --system-config-file   ./run_dir/system_config.json \\" >> $RFILE
echo "    --launcher-config-file ./run_dir/launcher_config.json" >> $RFILE

echo -e "\n# Generate training data from nekRS checkpoint files" >>$RFILE
echo "python ${NEKRS_HOME}/3rd_party/gnn/sr-gnn/nek_to_pt.py \\" >> $RFILE
echo "    --case_path $PWD \\" >> $RFILE
echo "    --target_snap_list turbChannel_p70.f00000 turbChannel_p70.f00001 turbChannel_p70.f00002 turbChannel_p70.f00003 turbChannel_p70.f00004 \\" >> $RFILE
echo "    --input_snap_list turbChannel_p10.f00000 turbChannel_p10.f00001 turbChannel_p10.f00002 turbChannel_p10.f00003 turbChannel_p10.f00004 \\" >> $RFILE
echo "    --target_poly_order 7 \\" >> $RFILE
echo "    --input_poly_order 1 \\" >> $RFILE
echo "    --n_element_neighbors 12" >> $RFILE

echo -e "\n# Train model" >>$RFILE
echo "mpiexec -n \${TOTAL_RANKS} -ppn \${RANKS_PER_NODE} --cpu-bind=list:${CPU_BIND_LIST} \\" >> $RFILE
echo "    python ${NEKRS_HOME}/3rd_party/gnn/sr-gnn/main.py \\" >> $RFILE
echo "    epochs=5 \\" >> $RFILE
echo "    n_element_neighbors=12 \\" >> $RFILE
echo "    n_messagePassing_layers=6 \\" >> $RFILE
echo "    data_dir=$PWD/pt_datasets \\" >> $RFILE
echo "    model_dir=$PWD/saved_models \\" >> $RFILE
echo "    2>&1 | tee train.log" >> $RFILE

echo -e "\n# Perform inference and generate files for visualization" >>$RFILE
echo "python ${NEKRS_HOME}/3rd_party/gnn/sr-gnn/postprocess.py \\" >> $RFILE
echo "    --model_path $PWD/saved_models/gnn_3_7_132_128_3_2_6_True.tar \\" >> $RFILE
echo "    --case_path $PWD \\" >> $RFILE
echo "    --output_name ${case} \\" >> $RFILE
echo "    --target_snap_list turbChannel_p70.f00000 \\" >> $RFILE
echo "    --input_snap_list turbChannel_p10.f00000 \\" >> $RFILE
echo "    --target_poly_order 7 \\" >> $RFILE
echo "    --input_poly_order 1 \\" >> $RFILE
echo "cd predictions/gnn_3_7_132_128_3_2_6_True" >> $RFILE
echo "$NEKRS_HOME/bin/nrsvis turbChannel_pred" >> $RFILE
echo "$NEKRS_HOME/bin/nrsvis turbChannel_error" >> $RFILE
echo "cd ../../" >> $RFILE
chmod u+x $RFILE

