#!/bin/bash
set -a

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <system name> <path to NEKRS_HOME>"
  exit 1
fi

SYSTEM="${1,,}"
NEKRS_HOME=$2
DEPLOYMENT="colocated"
VENV_PATH=""
PROJ_ID="datascience"
QUEUE="debug"

if [ ${SYSTEM} == "aurora" ]; then
  module load frameworks
elif [ ${SYSTEM} == "polaris" ]; then
  module use /soft/modulefiles/
  module load conda
  conda activate
  module load spack-pe-base cmake
fi

if [[ -z "$VENV_PATH" && ! -d ./_ssim ]]; then
  echo -e "\033[35mA Python venv was not specified, building one now ...\033[m"
  python -m venv --clear _ssim --system-site-packages
  source _ssim/bin/activate
 
  export CC=cc
  export CXX=CC
  export CUDNN_BASE=/soft/libraries/cudnn/cudnn-12-linux-x64-v9.1.0.70
  export CUDNN_LIBRARY=$CUDNN_BASE/lib/
  export CUDNN_INCLUDE_DIR=$CUDNN_BASE/include/
  export LD_LIBRARY_PATH=$CUDNN_LIBRARY:$LD_LIBRARY_PATH 
  export TORCH_CMAKE_PATH=$( python -c 'import torch;print(torch.utils.cmake_prefix_path)' )
  export TORCH_PATH=$( python -c 'import torch; print(torch.__path__[0])' )
  export LD_LIBRARY_PATH=$TORCH_PATH/lib:$LD_LIBRARY_PATH
  git clone https://github.com/rickybalin/SmartSim.git
  cd SmartSim
  git checkout rollback_aurora
  pip install -e .
  smart build -v --device cpu --torch_dir $TORCH_CMAKE_PATH --no_tf
  smart validate
  cd ..
  pip install torch_geometric==2.5.3
  VENV_PATH=${PWD}/_ssim/bin/activate
elif [ -d ./_ssim ]; then
  echo -e "\033[35mA Python venv was not specified, but fuond ./_ssim \033[m"
  VENV_PATH=${PWD}/_ssim/bin/activate
fi

echo "Setting up case:"
echo "    system: ${SYSTEM}"
echo "    NEKRS_HOME: ${NEKRS_HOME}"
echo "    deployment: ${DEPLOYMENT}"
echo

script_name=nrsrun_${SYSTEM}
if [ ${DEPLOYMENT} == "colocated" ]; then
  NODES=`cat $PBS_NODEFILE | wc -l`
  NEKRS_HOME=$NEKRS_HOME \
  PROJ_ID=$PROJ_ID \
  QUEUE=$QUEUE \
  DEPLOYMENT=$DEPLOYMENT \
  VENV_PATH=$VENV_PATH \
  ./${script_name} tgv $NODES 00:30
elif [ ${DEPLOYMENT} == "clustered" ]; then
  NODES=`cat $PBS_NODEFILE | wc -l`
  echo "Running on $NODES total nodes"
  echo "Enter the number of database node"
  read DB_NODES
  echo "simulation nodes"
  read SIM_NODES
  echo "and trainer nodes to use"
  read TRAIN_NODES
  NEKRS_HOME=$NEKRS_HOME \
  PROJ_ID=$PROJ_ID \
  QUEUE=$QUEUE \
  DEPLOYMENT=$DEPLOYMENT \
  VENV_PATH=$VENV_PATH \
  DB_NODES=$DB_NODES SIM_NODES=$SIM_NODES TRAIN_NODES=$TRAIN_NODES \
  ./${script_name} tgv $NODES 00:30
else
  echo Please select between clustered and colocated deployment of the workflow
fi

