#!/bin/bash
set -a

if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
  echo "Usages:"
  echo "    $0 <system name> <path to NEKRS_HOME>"
  echo "    $0 <system name> <path to NEKRS_HOME> <path to VENV>"
  exit 1
fi

SYSTEM="${1,,}"
NEKRS_HOME=$2
VENV_PATH=$4
PROJ_ID="datascience"
QUEUE="debug"

if [ ${SYSTEM} == "aurora" ]; then
  module load frameworks/2025.2.0
elif [ ${SYSTEM} == "polaris" ]; then
  module use /soft/modulefiles/
  module load conda
  conda activate
  module load spack-pe-base cmake
fi

if [[ -z "$VENV_PATH" && ! -d ./_pyg ]]; then
  echo -e "\033[35mA Python venv was not specified, building one now ...\033[m"
  python -m venv --clear _pyg --system-site-packages
  source _pyg/bin/activate
  TORCH_PATH=$( python -c 'import torch; print(torch.__path__[0])' )
  export LD_LIBRARY_PATH=$TORCH_PATH/lib:$LD_LIBRARY_PATH
  pip install torch_geometric==2.5.3
  
  if [ ${SYSTEM} == "aurora" ]; then
    git clone https://github.com/rusty1s/pytorch_cluster.git
    cd pytorch_cluster
    # Need to force the install to not link with OpenMP, change lines 53-54 to if False:
    sed -i 's/fopenmp/lgomp/' setup.py
    CXX=$(which dpcpp) python setup.py install
    cd ..
  elif [ ${SYSTEM} == "polaris" ]; then
    pip install torch-cluster
  fi

  pip install pymech
  VENV_PATH=${PWD}/_pyg/bin/activate
elif [ -d ./_pyg ]; then
  echo -e "\033[35mA Python venv was not specified, but found ./_pyg \033[m"
  VENV_PATH=${PWD}/_pyg/bin/activate
fi

echo "Setting up case:"
echo "    system: ${SYSTEM}"
echo "    NEKRS_HOME: ${NEKRS_HOME}"
echo "    VENV_PATH : ${VENV_PATH}"
echo

script_name=nrsrun_${SYSTEM}
NODES=`cat $PBS_NODEFILE | wc -l`
NEKRS_HOME=$NEKRS_HOME \
PROJ_ID=$PROJ_ID \
QUEUE=$QUEUE \
VENV_PATH=$VENV_PATH \
./${script_name} turbChannel $NODES 00:30

