#!/bin/bash -l
#PBS -A gpu_hack
#PBS -q gpu_hack_sm
#PBS -N nekrs-ml
#PBS -l walltime=01:00:00
#PBS -l select=1
#PBS -l place=scatter
#PBS -l filesystems=home:flare
#PBS -k doe
#PBS -j oe

cd $PBS_O_WORKDIR

SYSTEM="aurora"
NEKRS_HOME=/flare/datascience/balin/Nek/nekRS-ML/exe/nekRS
VENV_PATH=""
./gen_run_script $SYSTEM $NEKRS_HOME $VENV_PATH
./run.sh
