#!/bin/bash
set -e

#--------------------------------------
: ${QUEUE:="prod"}
: ${NEKRS_GPU_MPI:=0}
: ${NEKRS_BACKEND:="dpcpp"}
: ${RANKS_FOR_BUILD:=12}
: ${SIM_RANKS_PER_NODE:=12}
: ${TRAIN_RANKS_PER_NODE:=12}
: ${DEVICE_SKIP:=0}
: ${DEPLOYMENT:="clustered"}
: ${SIM_NODES:=1}
: ${TRAIN_NODES:=1}
: ${SIM_CPU_BIND_LIST:="1:8:16:24:32:40:53:60:68:76:84:92"}
: ${TRAIN_CPU_BIND_LIST:="1:8:16:24:32:40:53:60:68:76:84:92"}
: ${INFERENCE_CPU_BIND_LIST:="1:8:16:24:32:40:53:60:68:76:84:92"}
: ${OCCA_DPCPP_COMPILER_FLAGS:="-O3 -fsycl -fsycl-targets=intel_gpu_pvc -ftarget-register-alloc-mode=pvc:auto -fma"}
: ${ONEAPI_SDK:=""}
: ${FRAMEWORKS_MODULE:="frameworks"}
: ${VENV_PATH:=""}
#--------------------------------------

#--------------------------------------
# Set variables based on deployment type
if [ ${DEPLOYMENT} == "colocated"  ]; then
  SIM_NODES=$nodes
  TRAIN_NODES=$nodes
  SIM_RANKS_PER_NODE=6
  TRAIN_RANKS_PER_NODE=6
  DEVICE_SKIP=6
  SIM_CPU_BIND_LIST="1:8:16:24:32:40"
  TRAIN_CPU_BIND_LIST="53:60:68:76:84:92"
fi
SIM_PROCS=$(( SIM_NODES * SIM_RANKS_PER_NODE ))
TRAIN_PROCS=$(( TRAIN_NODES * TRAIN_RANKS_PER_NODE ))

#--------------------------------------
# Copy the .par file
cp ${1}.par.safe ${1}.par

#--------------------------------------
# Update the .box file to increase the mesh size linearly with the number of nodes
NZ=$(( 26*SIM_PROCS ))
LZ=$(echo "3.141592653 * $SIM_PROCS" | bc -l)
cp ${1}.box.safe ${1}.box
sed -i "s/NZ/${NZ}/g" ${1}.box
sed -i "s/LZ/${LZ}/g" ${1}.par

#--------------------------------------
# Run genbox from Nek5000 to generate the .re2 mesh file
if [ ! -d $NEKRS_HOME/Nek5000 ]; then
  CWD=$PWD
  cd $NEKRS_HOME
  git clone https://github.com/rickybalin/Nek5000.git
  cd Nek5000/tools
  FC=`which gfortran` ./maketools genbox
  cd $CWD
fi
$NEKRS_HOME/Nek5000/bin/genbox ${1}.box ${1}

#--------------------------------------
# Setup the case
source $NEKRS_HOME/bin/nrsqsub_utils
setup $# 1
chk_case $TOTAL_RANKS

#--------------------------------------
# Generate the affinity scripts
SAFF_FILE=affinity_nrs.sh
TAFF_FILE=affinity_ml.sh
if [ ${ZE_FLAT_DEVICE_HIERARCHY} == "COMPOSITE" ] || [[ -z "${ZE_FLAT_DEVICE_HIERARCHY}" ]]; then
  echo "#!/bin/bash" > $SAFF_FILE
  echo "num_gpus=\$1" >> $SAFF_FILE
  echo "shift" >> $SAFF_FILE
  echo "num_tiles=2" >> $SAFF_FILE
  echo "gpu_id=\$(((PALS_LOCAL_RANKID / \${num_tiles}) % \${num_gpus}))" >> $SAFF_FILE
  echo "tile_id=\$((PALS_LOCAL_RANKID % \${num_tiles}))" >> $SAFF_FILE
  echo "export ZE_AFFINITY_MASK=\$gpu_id.\$tile_id" >> $SAFF_FILE
  echo "exec \"\$@\"" >> $SAFF_FILE

  echo "#!/bin/bash" > $TAFF_FILE
  echo "num_gpus=\$1" >> $TAFF_FILE
  echo "offset=\$2" >> $TAFF_FILE
  echo "shift" >> $TAFF_FILE
  echo "shift" >> $TAFF_FILE
  echo "num_tiles=2" >> $TAFF_FILE
  echo "gpu_id=\$(((PALS_LOCAL_RANKID / \${num_tiles}) % \${num_gpus} + (offset / num_tiles) ))" >> $TAFF_FILE
  echo "tile_id=\$((PALS_LOCAL_RANKID % \${num_tiles}))" >> $TAFF_FILE
  echo "export ZE_AFFINITY_MASK=\$gpu_id.\$tile_id" >> $TAFF_FILE
  echo "exec \"\$@\"" >> $TAFF_FILE
elif [ ${ZE_FLAT_DEVICE_HIERARCHY} == "FLAT" ]; then
  echo "#!/bin/bash" > $SAFF_FILE
  echo "num_gpus=\$1" >> $SAFF_FILE
  echo "shift" >> $SAFF_FILE
  echo "gpu_id=\$((PALS_LOCAL_RANKID % \${num_gpus} ))" >> $SAFF_FILE
  echo "export ZE_AFFINITY_MASK=\$gpu_id" >> $SAFF_FILE
  echo "exec \"\$@\"" >> $SAFF_FILE

  echo "#!/bin/bash" > $TAFF_FILE
  echo "num_gpus=\$1" >> $TAFF_FILE
  echo "offset=\$2" >> $TAFF_FILE
  echo "shift" >> $TAFF_FILE
  echo "shift" >> $TAFF_FILE
  echo "gpu_id=\$((PALS_LOCAL_RANKID % \${num_gpus} + \${offset} ))" >> $TAFF_FILE
  echo "export ZE_AFFINITY_MASK=\$gpu_id" >> $TAFF_FILE
  echo "exec \"\$@\"" >> $TAFF_FILE
fi
chmod u+x $SAFF_FILE $TAFF_FILE

#--------------------------------------
# Generate the workflow config script
CFILE=config.yaml
echo "# Workflow config" > $CFILE
echo "scheduler: pbs" >> $CFILE
echo "system: aurora" >> $CFILE
echo "deployment: \"${DEPLOYMENT}\"" >> $CFILE
echo "debug: false" >> $CFILE
echo "" >> $CFILE
echo "# Run config" >> $CFILE
echo "run_args:" >> $CFILE
echo "    nodes: ${qnodes}" >> $CFILE
echo "    sim_nodes: ${SIM_NODES}" >> $CFILE
echo "    ml_nodes: ${SIM_NODES}" >> $CFILE
echo "    simprocs: ${SIM_PROCS}" >> $CFILE
echo "    simprocs_pn: ${SIM_RANKS_PER_NODE}" >> $CFILE
echo "    mlprocs: ${TRAIN_PROCS}" >> $CFILE
echo "    mlprocs_pn: ${TRAIN_RANKS_PER_NODE}" >> $CFILE
echo "    sim_cpu_bind: \"list:${SIM_CPU_BIND_LIST}\"" >> $CFILE
echo "    ml_cpu_bind: \"list:${TRAIN_CPU_BIND_LIST}\"" >> $CFILE
echo "" >> $CFILE
echo "# Simulation config" >> $CFILE
echo "sim:" >> $CFILE
echo "    executable: \"${NEKRS_HOME}/bin/nekrs\"" >> $CFILE
echo "    arguments: \"--setup ${case}.par --backend ${NEKRS_BACKEND} --device-id 0\"" >> $CFILE
echo "    affinity: \"./${SAFF_FILE}\"" >> $CFILE
echo "" >> $CFILE
echo "# Trainer config" >> $CFILE
echo "train:" >> $CFILE
echo "    executable: \"${NEKRS_HOME}/3rd_party/dist-gnn/main.py\"" >> $CFILE
#echo "    affinity: \"./${TAFF_FILE}\"" >> $CFILE
echo "    affinity: \"\"" >> $CFILE
echo "    arguments: \"device_skip=${DEVICE_SKIP} precision=bf16 phase1_steps=200 hidden_channels=256 n_mlp_hidden_layers=2 n_messagePassing_layers=8 backend=xccl halo_swap_mode=all_to_all_opt online=True client.backend=adios client.adios_transport=RDMA online_update_freq=20 time_dependency=time_dependent verbose=True\"" >> $CFILE
echo "" >> $CFILE
echo "# Inference config" >> $CFILE
echo "inference:" >> $CFILE
echo "    executable: \"${NEKRS_HOME}/3rd_party/dist-gnn/inference.py\"" >> $CFILE
#echo "    affinity: \"./${TAFF_FILE}\"" >> $CFILE
echo "    affinity: \"\"" >> $CFILE
echo "    arguments: \"model_task=inference rollout_steps=100 hidden_channels=256 n_mlp_hidden_layers=2 n_messagePassing_layers=8 backend=xccl halo_swap_mode=all_to_all_opt online=True client.backend=adios time_dependency=time_dependent verbose=True\"" >> $CFILE

#--------------------------------------
# Update the .par file with the ML options
PFILE=${case}.par
echo "" >> $PFILE
echo "[ML]" >> $PFILE
echo "gnnPolynomialOrder = 2" >> $PFILE
echo "adiosEngine = SST" >> $PFILE
echo "adiosTransport = RDMA" >> $PFILE
echo "adiosStream = async" >> $PFILE

#--------------------------------------
# Generate the run script
RFILE=run.sh
echo "#!/bin/bash -l" > $RFILE
echo "##PBS -S /bin/bash" >> $RFILE
echo "##PBS -N nekrs-ml" >> $RFILE
echo "##PBS -l walltime=${TIME}:00" >> $RFILE
echo "##PBS -l select=$NODES" >> $RFILE
echo "##PBS -l filesystems=home:flare" >> $RFILE
echo "##PBS -k doe" >> $RFILE
echo "##PBS -j oe" >> $RFILE
echo "##PBS -A $PROJ_ID" >> $RFILE
echo "##PBS -q $QUEUE" >> $RFILE
echo "#cd \$PBS_O_WORKDIR" >> $RFILE

echo -e "\nexport TZ='/usr/share/zoneinfo/US/Central'" >> $RFILE

echo -e "\necho Jobid: \$PBS_JOBID" >>$RFILE
echo "echo Running on host \`hostname\`" >>$RFILE
echo "echo Running on nodes \`cat \$PBS_NODEFILE\`" >>$RFILE

if ls $NEKRS_HOME/lib/libadios2*.so* 1> /dev/null 2>&1; then
  ADIOS2_BUILD=NEKRS
else
  ADIOS2_BUILD=SYSTEM
fi
echo "module load ${FRAMEWORKS_MODULE}" >> $RFILE
if [ ${ADIOS2_BUILD} == "SYSTEM" ]; then
  echo "module load adios2/git.86a48b9-cpu" >> $RFILE
fi
echo "source ${VENV_PATH}" >> $RFILE
echo "module list" >> $RFILE

echo -e "\nexport NEKRS_HOME=$NEKRS_HOME" >>$RFILE
echo "export OCCA_DPCPP_COMPILER_FLAGS=\"$OCCA_DPCPP_COMPILER_FLAGS\"" >> $RFILE
echo "export FI_CXI_RX_MATCH_MODE=hybrid" >> $RFILE # required by parRSB

# Temporary workaround while waiting on bugfix in runtime
echo "export UR_L0_USE_COPY_ENGINE=0" >> $RFILE

echo -e "\n# oneCCL env variables" >> $RFILE
echo "export CCL_PROCESS_LAUNCHER=pmix" >> $RFILE
echo "export CCL_ATL_TRANSPORT=mpi" >> $RFILE
echo "export CCL_KVS_MODE=mpi" >> $RFILE
echo "export CCL_ALLREDUCE_SCALEOUT=direct:0-1048576,rabenseifner:1048577-max" >> $RFILE
echo "export CCL_BCAST=double_tree" >> $RFILE
echo "export CCL_CONFIGURATION_PATH=\"\"" >> $RFILE
echo "export CCL_CONFIGURATION=cpu_gpu_dpcpp" >> $RFILE
echo "export CCL_KVS_CONNECTION_TIMEOUT=600" >> $RFILE
echo "export CCL_ZE_CACHE_OPEN_IPC_HANDLES_THRESHOLD=1024" >> $RFILE
echo "export CCL_KVS_USE_MPI_RANKS=1" >> $RFILE
echo "export CCL_ENABLE_SYCL_KERNELS=1" >> $RFILE
echo "export CCL_ALLTOALLV=naive" >> $RFILE
echo "export CCL_ALLTOALLV_SCALEOUT=naive" >> $RFILE
echo "export CCL_ALLTOALLV_MONOLITHIC_KERNEL=0" >> $RFILE

echo -e "\nulimit -c unlimited" >> $RFILE

echo -e "\n# ADIOS2 setup" >> $RFILE
if [ ${ADIOS2_BUILD} == "NEKRS" ]; then
  py_version=`python --version`
  parsed_version=$(echo ${py_version#Python } | awk -F. '{print $1"."$2}')
  echo "export PYTHONPATH=\$PYTHONPATH:${NEKRS_HOME}/lib/python${parsed_version}/site-packages" >> $RFILE
else
  echo "export PYTHONPATH=/opt/aurora/25.190.0/frameworks/aurora_frameworks-2025.2.0/lib/python3.10/site-packages:\$PYTHONPATH" >> $RFILE
fi
echo "export SstVerbose=1" >> $RFILE
echo "export OMP_PROC_BIND=spread" >> $RFILE
echo "export OMP_PLACES=threads" >> $RFILE
echo "if ls *.sst 1> /dev/null 2>&1" >> $RFILE
echo "then" >> $RFILE 
echo "    echo Cleaning up old .sst files" >> $RFILE
echo "    rm *.sst" >> $RFILE
echo "fi" >> $RFILE
echo "if ls *.bp 1> /dev/null 2>&1" >> $RFILE
echo "then" >> $RFILE
echo "    echo Cleaning up old .bp files" >> $RFILE
echo "    rm -r ./*.bp" >> $RFILE
echo "fi" >> $RFILE

echo -e "\n# precompilation" >> $RFILE
echo "if [ -d .cache ]; then" >> $RFILE
echo "  echo Cleaning up the cache" >> $RFILE
echo "  rm -rf .cache" >> $RFILE
echo "fi" >> $RFILE
CMD_build="mpiexec -n ${RANKS_FOR_BUILD} -ppn ${RANKS_FOR_BUILD} --cpu-bind list:${SIM_CPU_BIND_LIST} -- ./${SAFF_FILE} ${RANKS_FOR_BUILD} $bin --setup ${case} --backend ${NEKRS_BACKEND} --device-id 0 $extra_args --build-only ${RANKS_FOR_BUILD}"
add_build_CMD "$RFILE" "$CMD_build" "$TOTAL_RANKS"

echo -e "\n# actual run" >>$RFILE
echo "python driver.py" >> $RFILE
chmod u+x $RFILE

