#!/bin/bash
set -a

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <system name> <path to NEKRS_HOME>"
  exit 1
fi

SYSTEM="${1,,}"
NEKRS_HOME=$2
PROJ_ID="datascience"
QUEUE="debug-scaling"
NODES=4
TIME=1:00

if [ ${SYSTEM} == "aurora" ]; then
  module load frameworks
elif [ ${SYSTEM} == "polaris" ]; then
  module use /soft/modulefiles/
  module load conda
  conda activate
  module load spack-pe-base cmake
fi

echo -e "\033[35mBuilding sim.cpp ...\033[m"
export ADIOS2_DIR=${NEKRS_HOME}/lib/cmake/adios2/
cmake ./
make
  
echo 
echo "Setting up case:"
echo "    system: ${SYSTEM}"
echo "    NEKRS_HOME: ${NEKRS_HOME}"
echo

script_name=qsub_${SYSTEM} 
NEKRS_HOME=$NEKRS_HOME PROJ_ID=$PROJ_ID QUEUE=$QUEUE ./${script_name}

